#!/bin/bash
#@Author : Udit Karode <udit.karode@gmail.com>

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#!CHANGE THIS TO YOUR ROOT FOLDER!
root=/Users/udit/Class12File
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if [ "$#" == 0  ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]
then
	echo "!USAGE! "
	echo ""
	echo "-b/--build <filename> : Builds the file, and places a DOS executable in builds/."
	echo ""
	echo "-r/--run <filename> : Runs the filename (if present) from builds/."
	echo ""
	echo " NOTE: Filenames longer than 8 characters should have the first 6 characters and ~1 attached. If the filename is longer than 8 characters but there is a dot(.) before the eighth character, place a '~1' after the filename before the dot."
	echo ""
	echo "It is optional to run this script as root."
	echo ""
	echo "The system must have DOSBOX preinstalled."

elif [ "$#" == 2 ] && [ "$1" == "-b" ] || [ "$1" == "--build" ]
then
	echo "Doing magic with the file $2!"
	echo ""
	mkdir $root/.TEMPORARY_FOLDER_FOR_UKSCRIPT
	mkdir $root/.TEMPORARY_FOLDER_FOR_UKSCRIPT/TMPBUILDS
	cp $root/sources/$2 $root/.TEMPORARY_FOLDER_FOR_UKSCRIPT/src.cpp
	dosbox -c MOUNT\ C\ "$root" -c C: -c cd\ BIN -c tcc\ -IC:/BIN/\ -n../TEMPOR~1/TMPBUI~1/\ ../TEMPOR~1/src.cpp\>../logs/TCC.LOG -c exit > $root/logs/UCC-BUILD.LOG
	if [ "$(ls $root/.TEMPORARY_FOLDER_FOR_UKSCRIPT/TMPBUILDS)" == "" ]
	then
		echo "!! build failed !!"
		echo "check log for more details"
	else
		echo "!! build successful !!"
		mv $root/.TEMPORARY_FOLDER_FOR_UKSCRIPT/TMPBUILDS/*.EXE ~/Class12File/builds/$2.EXE
		echo "~ Built with UCC ~" >> $root/logs/TCC.LOG
	fi
	rm -r $root/.TEMPORARY_FOLDER_FOR_UKSCRIPT
	echo "-------------------------------"
	cat $root/logs/TCC.LOG
	echo "-------------------------------"

elif [ "$#" == 2 ] && [ "$1" == "-r" ] || [ "$1" == "--run" ]
then
	echo "Attempting to run $root/builds/$2"
	dosbox -c MOUNT\ C\ "$root/builds/" -c C: -c $2 -c exit > $root/logs/UCC-RUN.LOG
else
        echo "wut?"
fi
