#!/bin/bash

#   Copyright 2018 Udit Karode
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

VERSION=0.1
cd ..
root="$(pwd)"

function show_help(){
	echo -e "Usage: ucc [option] [argument]\n"
	echo -e "ucc --build <filename>: builds <filename> from the sources folder.\n"
	echo -e "ucc --run <filename>: runs <filename> from the builds folder.\n"
}

function inv_params(){
	echo -e "\nCommand not found. Use flag --help for command list."
}

function check_exists(){
	if [ ! -f "$1" ]; then
		echo -e "\nFATAL ERROR: File not found!\n"
		exit
	fi
}

case "$#" in
	"0")
		show_help
	;;

	"1")
		case "$1" in
			"-v"|"--version")
				echo -e "\nUCC for Windows v${VERSION}\n"
			;;

			"-i"|"--init"|"init")
				git clone https://github.com/uditkarode/ucc.git
				mv ucc/BIN .
				rm -rf ucc
				mkdir builds logs files sources headers
				echo -e "\nWorkspace initiated.\n"
			;;

			"-b"|"--build"|"-br")
				echo -e "\nEnter the filename to compile:\n"
				read fn
				if [ -f "$root/sources/${fn}.txt" ]; then
					mv $root/sources/${fn}.txt $root/sources/${fn}
				fi
				check_exists $root/sources/${fn}
				echo
				mkdir $root/.UCC
				mkdir $root/.UCC/TMPBUILDS
				cp $root/sources/$fn $root/.UCC/src.cpp

				dosbox -c MOUNT\ C\ "$root" -c C: -c cd\ BIN -c tcc\ -n..\\.UCC\\TMPBUI~1\\\ ..\\.UCC\\src.cpp\ GRAPHICS.LIB\>..\\logs\\TCC.LOG -c exit
					
				if [ -z "$(ls $root/.UCC/TMPBUILDS)" ]; then						build='failed'
					echo -e "\n!! build failed !!\n"
					echo
					echo -e "\nINFO: Printing $root/logs/TCC.LOG\n"
					echo -e "-------------------------------\n"
					cat $root/logs/TCC.LOG
					echo -e "\n------------------------------"
				else
					build='successful'
					echo -e "\n!! build successful !!\n"
					echo
					mv $root/.UCC/TMPBUILDS/*.EXE $root/builds/$fn.EXE>&-
					echo "	~ Built with UCC ~" >> $root/logs/TCC.LOG
			
					if [ ! -z "$(cat $root/logs/TCC.LOG | grep 'Warning')" ]; then
						grep '^Warning' $root/logs/TCC.LOG > $root/.ucc/.__warnings
						echo -e "${YELLOW}INFO: Compiler warning(s) found in build: ${RED}"
						echo
						cat $root/.ucc/.__warnings
						echo -e "${NC}"
					fi
				fi
				
				rm -rf $root/.UCC
				if [ "$1" = "-br" ] && [ "$build" = "successful" ]; then
					echo -e "\nINFO: build-run flag detected, running $fn"".EXE\n"
					cd $root/assets
					./ucc --specrun "$fn"".EXE"
				fi
			;;

			"-r"|"--run")
				echo -e "\nEnter the filename to run:\n"
				read fn
				check_exists $root/builds/${fn}
				cd $root/assets
				./ucc --specrun $fn
			;;

			"-h"|"--help")
				show_help
			;;

			*)
				inv_params
			;;
		esac
	;;

	"2")
		case "$1" in
			"--specrun")
				check_exists $root/builds/${2}
				cp $root/builds/$2 $root/files/RUN.EXE
				cp $root/BIN/EGAVGA.BGI $root/files/
				echo -e "INFO: Executing DOS file $2"
				dosbox -c MOUNT\ C\ "$root" -c C: -c cd\ files -c RUN -c exit
				rm $root/files/RUN.EXE
				rm $root/files/EGAVGA.BGI
			;;

			*)
				inv_params
			;;
		esac
	;;

	*)
		inv_params
	;;
esac